name: Deploy Hugo site

on:
  push:
    branches:
      - main   # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: true  # Fetch submodules
        fetch-depth: 0    # Ensure all history is fetched for building submodules

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true     # Use this for scss transpiler

    - name: Build Hugo site
      run: hugo

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Transfer files via SCP
      env:
        SERVER: ${{ secrets.SERVER }}           # Your server's IP or domain
        USERNAME: ${{ secrets.USERNAME }}       # Your SSH username
        PASSWORD: ${{ secrets.PASSWORD }}       # Your SSH password or use private key for better security
      run: |
        sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no -r ./public/* $USERNAME@$SERVER:myhome/navodila/.

